name: destroy-quizzey-backend

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Git Checkout
        uses: actions/checkout@v4

      # Package code
      - name: Package code
        working-directory: ./quizzey-backend/lambdas
        run: |
          zip lambdas.zip *.py
          pwd; ls -la 
          
          
      # Configure AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # Destroy Terraform
      - name: Destroy Terraform
        working-directory: ./quizzey-backend/terraform
        run: |
          rm -fr terraform.tfstate ||echo 'Does not exist'
          terraform init -input=false
          terraform workspace new ${GITHUB_REF##*/} || echo 'Already exists'
          terraform workspace select ${GITHUB_REF##*/} && terraform destroy -input=false -auto-approve
