name: destroy-quizzey-backend

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Git Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Destroy Terraform
        working-directory: ./quizzey-backend
        run: |
          rm -fr terraform.tfstate ||echo 'Does not exist'
          terraform init -input=false
          terraform workspace new ${GITHUB_REF##*/} || echo 'Already exists'
          terraform workspace select ${GITHUB_REF##*/} && terraform destroy -input=false -auto-approve
